---
Name: goldfinch-cli-supplier
---
SilverStripe\Dev\DevelopmentAdmin:
  registered_controllers:
    cli-supplier:
      controller: Goldfinch\CLISupplier\Controllers\CLISupplierController
      links:
        cli-supplier: 'CLI supplier'
